export default function Home() {
  return <main>
    <section className="hero" id="top">
      <header className="hero-header"><nav className="hero-nav" aria-label="Primary navigation"><a href="#top">Home</a><a href="#story">How It Works</a><a className="header-logo" href="#top" aria-label="Garden Guard home"><img src="/garden-guard-logo.png" alt="Garden Guard shield logo"/></a><a href="/updates">Roadmap</a><a href="#about">About</a><a className="visit-project" href="/updates">Visit Project</a></nav></header>
      <div className="hero-content"><h1>Garden<br/>Guard</h1><p className="hero-summary">AI wildlife monitoring that helps us understand what visits the garden — before deciding what to protect.</p><a className="hero-scroll" href="#story">Scroll for more <span aria-hidden="true">↓</span></a></div>
    </section>

    <section className="story" id="story" aria-label="Garden Guard wildlife snapshots"><div className="snapshot-gallery"><figure className="snapshot-card snapshot-card-turkey"><img src="/snapshot-bush-turkey.png" alt="Bush turkey captured near the Garden Guard plant bed"/></figure><figure className="snapshot-card snapshot-card-possum"><img src="/snapshot-possum.png" alt="Possum captured in the Garden Guard garden at night"/></figure><p>These snapshots are captured automatically as wildlife passes through the garden, helping build a real-world dataset for future AI model training.</p></div></section>

    <section className="about" id="about"><img className="about-photo" src="/bondy.jpg" alt="Bondy, creator of Garden Guard"/><div><p className="eyebrow">About the project owner</p><h2>Meet Bondy: builder, curious observer, and the person behind Garden Guard.</h2><p>Garden Guard began after Bondy&apos;s sister&apos;s plant disappeared overnight. Rather than simply blaming the wildlife, Bondy decided to find out who was visiting and why.</p><p>The project brings together everyday gardening, local computer vision, and a long-term interest in sharing space with the animals around us.</p><div className="social-links"><a className="social linkedin" href="https://www.linkedin.com/in/kunanon-thoonsap-48b56b239/" target="_blank" rel="noreferrer" aria-label="Visit Bondy on LinkedIn"><img src="/linkedin.webp" alt=""/><span>LinkedIn</span></a><span className="social youtube" aria-label="YouTube channel coming soon"><img src="/youtube.webp" alt=""/><span>YouTube soon</span></span></div></div></section>
    <section className="care"><p className="eyebrow">Wildlife care</p><h2>Curiosity first. Gentle action second.</h2><p>Garden Guard is designed to record and understand animal activity. Any future deterrents will be short, harmless, rate-limited, and always secondary to simple garden design choices.</p></section>
    <section className="future"><div className="future-copy"><p className="eyebrow">Get involved</p><h2>Help shape the future of Garden Guard.</h2><p>Follow the research journal, share your own garden sightings, or become an early tester when the prototype is ready.</p><a className="future-link" href="#top">Follow the project</a></div></section><footer><a className="brand" href="#top" aria-label="Garden Guard home"><img src="/garden-guard-logo.png" alt="Garden Guard"/></a><div className="footer-social"><span>Follow the project</span><a className="social linkedin" href="https://www.linkedin.com/in/kunanon-thoonsap-48b56b239/" target="_blank" rel="noreferrer" aria-label="Visit Bondy on LinkedIn"><img src="/linkedin.webp" alt=""/></a><span className="social youtube" aria-label="YouTube channel coming soon"><img src="/youtube.webp" alt=""/></span></div></footer>
  </main>
}
