export default function ProjectUpdates() {
  return (
    <main className="updates-page">
      <nav className="updates-nav"><a className="brand" href="/">Garden <i>Guard</i></a><a className="updates-back" href="/">Back to the project</a></nav>
      <section className="updates-hero"><p className="eyebrow">Project updates</p><p className="updates-date">August 2026 · Milestone 01</p><h1>The camera is live. YOLO is now watching the RTSP stream.</h1><p className="updates-lede">Garden Guard has moved from a concept and a public website into a working local computer-vision experiment.</p></section>
      <section className="updates-evidence" aria-labelledby="evidence-title"><div className="updates-caption"><p className="eyebrow">First successful detection</p><h2 id="evidence-title">A real-time person detection at 0.92 confidence.</h2><p>This frame comes directly from the camera’s RTSP feed after it was connected to YOLO. The bounding box and confidence score confirm that the detection pipeline is running end to end.</p><dl className="updates-facts"><div><dt>Input</dt><dd>Live RTSP camera stream</dd></div><div><dt>Model</dt><dd>YOLO object detection</dd></div><div><dt>Result</dt><dd>Person · 0.92 confidence</dd></div></dl></div><figure className="detection-frame"><img src="/yolo-rtsp-person-detection.png" alt="YOLO detecting a person in a live camera stream with 0.92 confidence" /><figcaption><span>Live test</span> YOLO reading the RTSP camera feed</figcaption></figure></section>
      <section className="updates-next"><p className="eyebrow">What this unlocks</p><h2>From camera frames to meaningful garden observations.</h2><div className="updates-grid"><article><b>01</b><h3>Train for garden visitors</h3><p>Test and improve detection for bush turkeys, possums, and other animals around the garden bed.</p></article><article><b>02</b><h3>Save useful events</h3><p>Store confirmed sightings with a time, species, confidence score, and image or video reference.</p></article><article><b>03</b><h3>Learn from the nights</h3><p>Turn the event history into patterns, research notes, and eventually gentle, rule-based protection.</p></article></div></section>
      <section className="updates-note"><p>Garden Guard processes the camera feed locally. The long-term goal is to understand the wildlife sharing the garden—not simply to chase it away.</p></section><footer><a className="brand" href="/">Garden <i>Guard</i></a><a href="/">Explore the main project</a></footer>
    </main>
  )
}
